dns:
  enable: true # 是否启用dns false
  prefer-h3: false # DOH 优先使用 http/3
  ipv6: true # ipv6 解析开关
  listen: 0.0.0.0:53 # DNS 服务监听，仅支持 udp
  enhanced-mode: fake-ip # 模式：redir-host或fake-ip
  fake-ip-range: 198.18.0.1/16 #
  use-hosts: true # 是否回应配置中的 hosts，默认 true
  use-system-hosts: false # 是否查询系统 hosts，默认 true，我们不用系统 hosts
  fake-ip-filter: # fake ip 黑名单列表，如果你不知道这个参数的作用，请勿修改
    - '*.lan'
    - '*.local'
    - '*.arpa'
    - time.*.com
    - ntp.*.com
    - time.*.com
    - +.market.xiaomi.com
    - localhost.ptlogin2.qq.com
    - '*.msftncsi.com'
    - www.msftconnecttest.com
  fake-ip-filter-mode: blacklist
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
    - 2400:3200::1
    - 2402:4e00:1::
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
  proxy-server-nameserver:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
  direct-nameserver:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
  respect-rules: true # 配置查询域名使用的 DNS 服务器
